// Default hardcoded catalog data for instant zero-latency sitemap rendering.
// Dynamic titles are loaded asynchronously in the background.

export const DEFAULT_CATEGORIES = [
  {
    title: "Home Catalog",
    path: "/",
    description: "Trending movies, popular series, anime spotlight, and featured recommendations.",
    priority: "1.0",
    changeFreq: "Daily",
  },
  {
    title: "Movies Directory",
    path: "/movies",
    description: "Extensive collection of cinema blockbusters, Hindi dubbed releases, classics, and indie films.",
    priority: "0.95",
    changeFreq: "Daily",
  },
  {
    title: "TV Series Hub",
    path: "/tv-series",
    description: "Full episodic seasons, trending television series, and multi-season dramas.",
    priority: "0.95",
    changeFreq: "Daily",
  },
  {
    title: "Anime & Animation",
    path: "/animation",
    description: "Top anime releases, animated feature films, Japanese OVAs, and animated series.",
    priority: "0.9",
    changeFreq: "Daily",
  },
  {
    title: "Top Rankings",
    path: "/ranking",
    description: "Highest-rated and most-watched titles ranked across cinema, series, and anime.",
    priority: "0.85",
    changeFreq: "Daily",
  },
  {
    title: "Songs & Audio Catalog",
    path: "/songs",
    description: "Free streaming music, soundtrack collections, and artist discovery powered by Audius.",
    priority: "0.85",
    changeFreq: "Daily",
  },
  {
    title: "Live Search & Discovery",
    path: "/search",
    description: "Instant title search with smart suggestion indexing across the full catalog.",
    priority: "0.7",
    changeFreq: "Weekly",
  },
];

export const DEFAULT_GENRES = [
  { name: "Action", slug: "action", path: "/search?q=Action" },
  { name: "Drama", slug: "drama", path: "/search?q=Drama" },
  { name: "Comedy", slug: "comedy", path: "/search?q=Comedy" },
  { name: "Sci-Fi & Fantasy", slug: "scifi", path: "/search?q=Sci-Fi" },
  { name: "Animation & Anime", slug: "animation", path: "/animation" },
  { name: "Thriller & Crime", slug: "thriller", path: "/search?q=Thriller" },
  { name: "Romance", slug: "romance", path: "/search?q=Romance" },
  { name: "Horror", slug: "horror", path: "/search?q=Horror" },
  { name: "Hindi Dubbed", slug: "hindi", path: "/search?q=Hindi" },
  { name: "Adventure", slug: "adventure", path: "/search?q=Adventure" },
  { name: "Mystery", slug: "mystery", path: "/search?q=Mystery" },
  { name: "Documentary", slug: "documentary", path: "/search?q=Documentary" },
];

export const DEFAULT_LEGAL = [
  {
    title: "Terms of Service",
    path: "/terms",
    description: "Terms governing use of Offstream website and mobile applications.",
    priority: "0.4",
    changeFreq: "Monthly",
  },
  {
    title: "Privacy Policy",
    path: "/privacy",
    description: "Data handling, device permissions, and user privacy protection commitments.",
    priority: "0.4",
    changeFreq: "Monthly",
  },
  {
    title: "Help & Support",
    path: "/support",
    description: "Frequently asked questions, troubleshooting guides, and customer contact.",
    priority: "0.5",
    changeFreq: "Monthly",
  },
];

export const DEFAULT_USER_PAGES = [
  {
    title: "User Profiles",
    path: "/profiles",
    description: "Manage multiple viewing profiles for personalized recommendations.",
  },
  {
    title: "Watch History",
    path: "/history",
    description: "Review recently played titles and resume playback anytime.",
  },
  {
    title: "Account Settings",
    path: "/settings",
    description: "Configure preferences, player options, audio, and device sync.",
  },
];

export const DEFAULT_TITLES = [
  {
    slug: "house-of-the-dragon",
    name: "House of the Dragon",
    year: "2024",
    rating: "8.4",
    badge: "Trending",
    category: "TV Series",
  },
  {
    slug: "x-men-97",
    name: "X-Men '97",
    year: "2024",
    rating: "8.9",
    badge: "Popular",
    category: "Animation",
  },
  {
    slug: "onslaught",
    name: "Onslaught",
    year: "2024",
    rating: "7.2",
    badge: "Featured",
    category: "Movies",
  },
  {
    slug: "fall-2-deadpoint",
    name: "Fall 2: Deadpoint",
    year: "2024",
    rating: "6.8",
    badge: "Action",
    category: "Movies",
  },
  {
    slug: "batman-caped-crusader",
    name: "Batman: Caped Crusader",
    year: "2024",
    rating: "7.5",
    badge: "DC Universe",
    category: "Animation",
  },
  {
    slug: "coven-academy",
    name: "Coven Academy",
    year: "2024",
    rating: "6.5",
    badge: "Fantasy",
    category: "TV Series",
  },
  {
    slug: "carrie",
    name: "Carrie",
    year: "2024",
    rating: "6.9",
    badge: "Horror",
    category: "Movies",
  },
  {
    slug: "the-lord-of-the-rings-the-rings-of-power",
    name: "The Lord of the Rings: The Rings of Power",
    year: "2024",
    rating: "7.0",
    badge: "Epic",
    category: "TV Series",
  },
  {
    slug: "below",
    name: "Below",
    year: "2024",
    rating: "6.4",
    badge: "Thriller",
    category: "Movies",
  },
  {
    slug: "merry-berry-love",
    name: "Merry Berry Love",
    year: "2024",
    rating: "6.2",
    badge: "Romance",
    category: "Movies",
  },
  {
    slug: "black-clover-season-2",
    name: "Black Clover Season 2",
    year: "2024",
    rating: "8.3",
    badge: "Anime",
    category: "Animation",
  },
  {
    slug: "ajosepo-2-the-gathering",
    name: "Ajosepo 2: The Gathering",
    year: "2024",
    rating: "6.1",
    badge: "Drama",
    category: "Movies",
  },
  {
    slug: "fallout",
    name: "Fallout",
    year: "2024",
    rating: "8.4",
    badge: "Sci-Fi",
    category: "TV Series",
  },
  {
    slug: "shogun",
    name: "Shōgun",
    year: "2024",
    rating: "8.7",
    badge: "Historical",
    category: "TV Series",
  },
  {
    slug: "the-boys",
    name: "The Boys",
    year: "2024",
    rating: "8.7",
    badge: "Action",
    category: "TV Series",
  },
  {
    slug: "dune-part-two",
    name: "Dune: Part Two",
    year: "2024",
    rating: "8.5",
    badge: "Blockbuster",
    category: "Movies",
  },
  {
    slug: "deadpool-and-wolverine",
    name: "Deadpool & Wolverine",
    year: "2024",
    rating: "7.8",
    badge: "Marvel",
    category: "Movies",
  },
  {
    slug: "oppenheimer",
    name: "Oppenheimer",
    year: "2023",
    rating: "8.9",
    badge: "Oscar Winner",
    category: "Movies",
  },
  {
    slug: "interstellar",
    name: "Interstellar",
    year: "2014",
    rating: "8.7",
    badge: "Sci-Fi Classic",
    category: "Movies",
  },
  {
    slug: "the-dark-knight",
    name: "The Dark Knight",
    year: "2008",
    rating: "9.0",
    badge: "Top Rated",
    category: "Movies",
  },
  {
    slug: "inception",
    name: "Inception",
    year: "2010",
    rating: "8.8",
    badge: "Mind-Bending",
    category: "Movies",
  },
  {
    slug: "jujutsu-kaisen",
    name: "Jujutsu Kaisen",
    year: "2023",
    rating: "8.6",
    badge: "Top Anime",
    category: "Animation",
  },
  {
    slug: "demon-slayer",
    name: "Demon Slayer: Kimetsu no Yaiba",
    year: "2024",
    rating: "8.7",
    badge: "Anime",
    category: "Animation",
  },
  {
    slug: "solo-leveling",
    name: "Solo Leveling",
    year: "2024",
    rating: "8.4",
    badge: "Trending Anime",
    category: "Animation",
  },
  {
    slug: "attack-on-titan",
    name: "Attack on Titan",
    year: "2023",
    rating: "9.1",
    badge: "Masterpiece",
    category: "Animation",
  },
  {
    slug: "one-piece",
    name: "One Piece",
    year: "2024",
    rating: "8.9",
    badge: "Legendary",
    category: "Animation",
  },
  {
    slug: "stranger-things",
    name: "Stranger Things",
    year: "2024",
    rating: "8.7",
    badge: "Netflix Hit",
    category: "TV Series",
  },
  {
    slug: "breaking-bad",
    name: "Breaking Bad",
    year: "2013",
    rating: "9.5",
    badge: "All-Time Best",
    category: "TV Series",
  },
  {
    slug: "game-of-thrones",
    name: "Game of Thrones",
    year: "2019",
    rating: "9.2",
    badge: "HBO",
    category: "TV Series",
  },
  {
    slug: "loki",
    name: "Loki",
    year: "2023",
    rating: "8.2",
    badge: "Marvel Studios",
    category: "TV Series",
  },
];
